Needle implementation first pass
lukesneeringer/mock-duck pull request #8
Opened 2017-08-20 23:04 UTC by NebonRevurg

Still have some unanswered questions about needle, but wanted to create a PR for feedback.

Do we want to handle the AttributeError and TypeErrors that can be raised if a user mismatches types or does a search that wouldn't normally be supported by `__compare__`?

2017-08-20 23:25 UTC, lukesneeringer commented
> Do we want to handle the AttributeError and TypeErrors that can be raised if a user mismatches types or does a search that wouldn't normally be supported by `__compare__`?

No.

2017-08-20 23:35 UTC, lukesneeringer requested changes

2017-08-20 23:35 UTC, lukesneeringer commented on duck/ornithology.py
> +        predicate (Callable): The predicate to use to test.
`predicate (Callable -> bool): The predicate to use as a test. It should return a boolean.`

2017-08-20 23:35 UTC, lukesneeringer commented on duck/ornithology.py
> +        predicate (Callable): The predicate to use to test.
Need to check and make sure that is the correct docstring syntax.

2017-08-20 23:35 UTC, lukesneeringer commented on duck/ornithology.py
> +        super(Needle, self).__init__(lambda t: haystack.__contains__(t))
`lambda haystack: needle in haystack` (Use `h` or `hay` if `haystack` is too long, which I suspect it is.)

It is pretty rare that you want to call dunder methods directly. You usually want to _define_ them and then call the Python operators; in this case, that means `needle in haystack` and not `haystack.__contains__(needle)`.

2017-08-20 23:35 UTC, lukesneeringer commented on duck/ornithology.py
> +        # todo: we may need to use a helper function to capture an
Let those exceptions bubble.

2017-08-20 23:35 UTC, lukesneeringer commented on duck/ornithology.py
> +    def __init__(self, haystack):
The argument to `Needle()` should be _the needle_, not the haystack.
The usage is intended to be something like this.

Actual call:

```python
my_method('Lorem ipsum dolor set amet blah blah blah blah...')
```

Proving it in the mock:

```python
mock_method.assert_called_once_with(duck.Needle('Lorem ipsum'))
```

2017-08-20 23:35 UTC, lukesneeringer commented on tests/test_ornithology.py
> +        assert Needle(collect) == "foo"
All of these tests are backwards (because the implementation is backwards).

2017-08-21 00:15 UTC, NebonRevurg commented on duck/ornithology.py
> +        super(Needle, self).__init__(lambda t: haystack.__contains__(t))
2 AM brain misread the doc. Changes made.

2017-08-21 00:47 UTC, lukesneeringer reviewed
This looks like it is probably there, other than some debugging code and such. Let me know when it is ready for a final pass.

2017-08-21 00:47 UTC, lukesneeringer commented on tests/test_ornithology.py
> +    try:
Is the try/except debugging code?

2017-08-21 00:47 UTC, lukesneeringer commented on tests/test_ornithology.py
>      :return:
This can go away.

2017-08-21 00:59 UTC, NebonRevurg commented
Should be ready to go unless there's other changes that need to happen.

2017-08-21 00:59 UTC, NebonRevurg commented on tests/test_ornithology.py
> +    try:
Yep. Removed.

2017-08-21 01:00 UTC, NebonRevurg commented on tests/test_ornithology.py
>      :return:
auto docstring formatting snuck in. It's gone now

2017-08-21 01:05 UTC, lukesneeringer approved these changes
LGTM with a nitpick on the comments.

2017-08-21 01:05 UTC, lukesneeringer commented on tests/test_ornithology.py
> +    # Reverse order tests
We should _either_ remove these comments, or wrap it in `if sys.version_info < (3, 5):`

My vote is outright removal.

2017-08-21 01:05 UTC, lukesneeringer commented on tests/test_ornithology.py
> +    # Reverse order tests
Same with this.

2017-08-21 01:10 UTC, NebonRevurg commented on tests/test_ornithology.py
> +    # Reverse order tests
It has been done!

2017-08-21 01:11 UTC, merged